lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, get_friend_list

urlpatterns = [
		url(r'^$', index, name='index'),
		url(r'^add-friend/$', add_friend, name='add-friend'),
		url(r'^validate-npm/$', validate_npm, name='validate-npm'),
		url(r'^delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
		url(r'^friend-list/$', friend_list, name='friend-list'),
		url(r'^get-friend-list/$', get_friend_list, name='get-friend-list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^lab-1/', include(lab_1,namespace='lab-1')),
	url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^$', RedirectView.as_view(url="/lab-2/",permanent="true"), name='index'),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4,namespace='lab-4')),
	url(r'^lab-5/', include(lab_5, namespace='lab-5')),
	url(r'^lab-6/', include(lab_6, namespace='lab-6')),
	url(r'^lab-7/', include(lab_7, namespace='lab-7')),
	url(r'^lab-8/', include(lab_8, namespace='lab-8')),
	url(r'^lab-9/', include(lab_9, namespace='lab-9')),
	url(r'^lab-10/', include(lab_10, namespace='lab-10')),
]

lab_7/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)
	added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.forms.models import model_to_dict
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    page = request.GET.get('page', '1')
    try:
        page = int(page)
        response_mahasiswa = csui_helper.instance.get_mahasiswa_list(page=page)
        mahasiswa_list = response_mahasiswa["results"]
    except Exception:
        return HttpResponseRedirect('/lab-7/')

    friend_list = Friend.objects.all()
    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list, "next_page": page + 1, "prev_page": page - 1}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)


@csrf_exempt
def get_friend_list(request):
    # data = serializers.serialize('json', Friend.objects.all())
    data = [model_to_dict(friend) for friend in Friend.objects.all()]
    return JsonResponse({'results': data})

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        if (not is_npm_taken(npm)):
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return JsonResponse(data)
        return JsonResponse({'message': 'mahasiswa sudah ditambahkan sebagai teman'}, status=400)

@csrf_exempt
def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return JsonResponse({'message': 'mahasiswa dihapus dari daftar teman'}, status=204)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    is_taken = is_npm_taken(npm)
    data = {
        'is_taken': is_taken
    }
    return JsonResponse(data)


def is_npm_taken(npm):
    return (Friend.objects.filter(npm=npm).count() != 0)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> My Friend(s) </h2>
                <div id="friend-list" class="list-group">

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
    <script>
        var removeFriend = function(id) {
            $.ajax({
                method: "DELETE",
                url: "/lab-7/delete-friend/" + id + "/",
                success : function (response) {
                    console.log('sukses');
                    $('#friends-' + id).remove();
                },
                error : function (error) {
                    console.log('gagal');
                }
            });
        };

        $( document ).ready(function () {
            //ambil daftar teman dari database
            $.ajax({
                method: "GET",
                url: "{% url "lab-7:get-friend-list" %}",
                success: function (response) {
                    friends = response.results;
                    for (i = 0; i < friends.length; i++){
                        html = '<a class="list-group-item clearfix" id="friends-' + friends[i].id + '">' +
                            friends[i].friend_name + ' (' + friends[i].npm + ')' +
                            '<span class="pull-right">' +
                            '<span class="btn btn-xs btn-default" onClick=removeFriend(' + friends[i].id + ')>' +
                            'Hapus teman</span></span></a>';
                        $("#friend-list").append(html) //menampilkan list teman ke halaman
                    }
                },
                error: function(error){
                    console.log('Failed to load friend list'); //log error
                }
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                {% for i in "xxxxxxxxxx" %}
                    {% widthratio forloop.counter0 1 10 as a  %}
                    {% widthratio forloop.counter 1 10 as b %}
                    {% with a|stringformat:"s" as awal %}
                    {% with b|stringformat:"s" as akhir %}
                    {% with ":"|add:b as pertama %}
                    {% with awal|add:pertama as lolo %}
                    <div class="list-group{{ forloop.counter }}">
                            {% if mahasiswa_list|slice:lolo %}
                                {% for mahasiswa in mahasiswa_list|slice:lolo %}
                                    <a class="list-group-item clearfix">
                                        {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                        <span class="pull-right">
                                          <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                            Tambah sebagai teman
                                          </span>
                                        </span>
                                    </a>
                                {% endfor %}
                            {% else %}
                                <div class="alert alert-danger text-center">
                                    <strong>Opps!</strong> Mahasiswa tidak ada
                                </div>
                            {% endif %}
                    </div>
                  {% endwith %}
                  {% endwith %}
                  {% endwith %}
                  {% endwith %}
                {% endfor %}
                <div style="text-align:center;width:100%;">
                  <div class="pagination" style="display:inline-block;"></div>
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center" id="alertin">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
  $(document).ready(function(){
    for(i=1;i<11;i++){
      if(i!=1){
        $('.list-group'+i).hide();
      }
      $('.pagination').append('<button class="abcd" onClick=next('+i+')>'+i+'</button>');

    }
  });

  var next = function(id){
    $('.list-group'+id).fadeIn();
    for(i=1;i<11;i++){
      if(i!=id){
        $('.list-group'+i).hide();
      }
    }

  };

 var addFriend = function(nama, npm, alamat, ttl, prodi) {
     $.ajax({
         method: "POST",
         url: "{% url "lab-7:add-friend" %}",
         data: {name: nama, npm: npm, alamat: alamat, ttl: ttl, prodi: prodi},
         success : function (friend) {
             if (friend.valid){
               html = '<a class="list-group-item clearfix">' +
                 friend.teman.friend_name + ' (' +
                 friend.teman.npm
                 + ') </a>';
               $("#friend-list").append(html).show('slow');
               $("#alertin").hide();
             } else {
               alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
             }
         },
         error : function (error) {
             alert("error")
         }
     });
 };

 $("#add-friend").on("submit", function () {
    name = $("#field_name").val()
    npm = $("#field_npm").val()
    addFriend(name, npm, '', '', '')
    event.preventDefault();
 });

 $("#field_npm").change(function () {
     console.log( $(this).val() );
     npm = $(this).val();
     $.ajax({
         method: "POST",
         url: '{% url "lab-7:validate-npm" %}',
         data: {
             'npm': npm
             },
             dataType: 'json',
             success: function (data) {
                 console.log(data)
                 if (data.is_taken) {
                     alert("Mahasiswa dengan npm seperti ini sudah ada");
                 }
             }
         });
     });
 </script>
{% endblock %}